name: Run Elytra Project

on:
  push:
    branches:
      - main
      - github-actions-test

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore autoElytraETF/autoElytraETF.csproj

      - name: Build project
        run: dotnet build autoElytraETF/autoElytraETF.csproj --configuration Release --no-restore

      - name: Create destination directory if not exist
        run: mkdir -p assets/minecraft/optifine/random/entity/equipment/wings

      - name: Run the project
        run: dotnet run --project autoElytraETF/autoElytraETF.csproj

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/
          git diff --cached --quiet || git commit -m "Update assets by elytraAutoETF"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}