name: Run Elytra Project

on:
  push:
    branches:
      - main
      - github-actions-test

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore autoElytraETF/autoElytraETF.csproj

      - name: Build project
        run: dotnet build autoElytraETF/autoElytraETF.csproj --configuration Release --no-restore

      - name: Create destination directory if dont exist
        run: mkdir -p assets/minecraft/optifine/random/entity/equipment/wings

      - name: Run the project
        run: dotnet run --project autoElytraETF/autoElytraETF.csproj